name: "RPi2 MQTT GPIO Bridge"
version: "1.0.0"
slug: "rpi2_mqtt_bridge"
description: "MQTT gateway for GPIO using rpi2home-assistant"
arch:
  - armhf
  - armv7
  - aarch64
startup: "application"
boot: "auto"
host_network: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_RESOURCE
# +++ НОВАЯ СТРОКА: Указываем готовый образ +++
image: "ghcr.io/f18m/rpi2home-assistant-{arch}"
options:
  config_file: "/config/rpi2home-assistant.yaml"
schema:
  config_file: "str"
