name: "RPi2 MQTT GPIO Bridge"
version: "1.0.0"
slug: "rpi2_mqtt_bridge"
description: "MQTT gateway for GPIO using rpi2home-assistant"
arch:
  - armhf
  - armv7
  - aarch64
startup: "application"
boot: "auto"
host_network: true
privileged: true
options:
  config_file: "/config/rpi2home-assistant.yaml"
schema:
  config_file: "str"
